# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :s1 => {
        net: [
            { adapter: 2, virtualbox__intnet: "net1" },
            { adapter: 3, virtualbox__intnet: "net1" },
        ],
    },
    :s2 => {
        net: [
            { adapter: 2, virtualbox__intnet: "net1" },
            { adapter: 3, virtualbox__intnet: "net1" },
        ],
    }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = "centos/7"
            box.vm.box_check_update = false
            box.vm.host_name = boxname.to_s

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end

            box.vm.provision "shell", inline: "yum install -y tcpdump"
        end
    end
end

