# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :s1 => {
        net: [
            { ip: '10.10.10.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net1" },
        ],
    },
    :s2 => {
        net: [
            { ip: '10.10.10.3', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net2" },
        ],
    },
    :router => {
        net: [
            { adapter: 2, virtualbox__intnet: "net1" },
            { adapter: 3, virtualbox__intnet: "net2" },
        ],
        isRouter: true,
    },
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = "centos/7"
            box.vm.box_check_update = false
            box.vm.host_name = boxname.to_s

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end

            box.vm.provision "shell", inline: "yum install -y tcpdump"

            if boxconfig[:isRouter] then
                box.vm.provision "shell", inline: <<-SHELL
                    echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf
                    sysctl -p /etc/sysctl.conf
                SHELL
            end

            if boxconfig[:routes] then
                boxconfig[:routes].each do |route|
                    box.vm.provision "shell" do |s|
                        s.inline = <<-SHELL
                            nmcli connection modify "$1" +ipv4.routes "$2 $3"
                            nmcli connection up "$1"
                        SHELL
                        s.args = [route[:connection], route[:dst], route[:src]]
                    end
                end
            end

            if boxconfig[:gateway] then
                box.vm.provision "shell" do |s|
                    s.inline = <<-SHELL
                        nmcli connection modify "$1" ipv4.gateway "$2"
                        nmcli connection up "$1"
                    SHELL
                    s.args = [boxconfig[:gateway][:connection], boxconfig[:gateway][:ip]]
                end
            end
        end
    end
end

