# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    echo "Installing Puppet agent..."
    sudo rpm -Uvh https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
    sudo yum install puppet-agent -y
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.manifest_file = "init.pp"
	puppet.options = "--verbose"
  end
end
